package listasDeTestesDaTransformacaoParaXMLDosComponentesGedix;

public interface ListaDeTestesDaTransformacaoParaXMLDoComponenteGedixComOpcoes {
	
    public void dadoUmComponenteGedixComOpçõesPodeGerarOsElementosDasOpções();
	
	public void podeGerarOXMLCompletoComAsOpçõesComoFilhosDAMarcaçãoXMLDoComponenteGedixComOpções();

}
