install:
	cp vimrc $(HOME)/.vimrc
	cp -pr .vim $(HOME)
	mkdir -p $(HOME)/.vim/autoload
	mkdir -p $(HOME)/.vim/bundle
	curl -Sso $(HOME)/.vim/autoload/pathogen.vim https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
