" This must be first, because it changes other options as side effect
set nocompatible
set autoindent       " always set autoindenting on
set copyindent       " copy the previous indentation on autoindenting
set smarttab         " insert tabs on the start of a line according to shiftwidth, not tabstop
set undolevels=1000  " use many muchos levels of undo
set nobackup
set noswapfile
set wildignore=*.swp,*.bak,*.pyc,*.class,*.o,*.so
set is scs magic  "Opções de Busca
set history=10000 "Grava as últimas linhas do código
set nu "Numeração de linhas
set sm "Par de parênteses
set ts=4 "Seta aonde o tab para
set sw=4 "Número de colunas para ShiftWidth
set et "Espaços no lugar de tabulação
set showcmd "Mostra comandos incompletos
set hlsearch "Prints searched words
set nocp
set hidden "Dont have to save changes on current buffer when opening new buffer
set showmode
set wildmenu
set wildmode=list:longest,full

" Get that filetype stuff happening
filetype on
filetype plugin on
filetype indent on

syntax on

autocmd filetype python set expandtab

"Move faster when screen is splitted
map <C-DOWN> <C-w><DOWN>
map <C-UP> <C-w><UP>
map <C-LEFT> <C-w><LEFT>
map <C-RIGHT> <C-w><RIGHT>

"Faster navigation in buffer (hacking vim, kim schulz)
map <A-right> <ESC>:bn<CR>
map <A-left> <ESC>:bp<CR>

"Fast Tab navigation 
nnoremap <C-S-left> :tabprevious<CR>
nnoremap <C-S-right>   :tabnext<CR>
inoremap <C-S-left> <Esc>:tabprevious<CR>
inoremap <C-S-right>   <Esc>:tabnext<CR>

"Fast building with tests ;-)
nnoremap <C-b> :!make check<CR>

"Fast commiting/diffing, also with tests ;-)
"nnoremap <TODO> :!svn commit<CR>
"inoremap <TODO> :!svn commit<CR>
"nnoremap <TODO> :!svn diff<CR>
"inoremap <TODO> :!svn diff<CR>
