#ifndef WINDOW_SIZE_H
#define WINDOW_SIZE_H

enum WindowSize {
    WINDOW_WIDTH  = 800,
    WINDOW_HEIGHT = 750,
    WINDOW_GARAGE_Y = 680,
    WINDOW_GARAGE_X = WINDOW_WIDTH / 2
};

#endif // WINDOW_SIZE_H
