# maintain examples
all:

test:
	lua ../ChunkBake.lua cf.asm -o cf-cb.out
	lua ../ChunkBake.lua echo.asm -o echo-cb.out
	lua ../ChunkBake.lua env.asm -o env-cb.out
	lua ../ChunkBake.lua hello.asm -o hello-cb.out
	lua ../ChunkBake.lua luac.asm -o luac-cb.out
	lua ../ChunkBake.lua printf.asm -o printf-cb.out
	lua ../ChunkBake.lua undefined.asm -o undefined-cb.out
